import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";

import { parseCssValueDefinition } from "../../dist/internal/grammar/value-definition.js";

const check = process.argv.includes("--check");
const root = new URL("../../", import.meta.url);
const sourcesUrl = new URL("test/fixtures/upstream/sources.json", root);
const outputUrl = new URL("src/internal/generated/css-data.ts", root);

const sources = expectRecord(
  JSON.parse(await readFile(sourcesUrl, "utf8")),
  "test/fixtures/upstream/sources.json"
);
const pin = expectRecord(sources.webref, "sources.webref");
const packageName = expectString(pin.package, "sources.webref.package");
const tarballUrl = expectString(pin.tarball, "sources.webref.tarball");
const integrity = expectString(pin.integrity, "sources.webref.integrity");
const sha1 = expectString(pin.sha1, "sources.webref.sha1");

const response = await globalThis.fetch(tarballUrl);
if (!response.ok) {
  throw new Error(
    `Unable to download ${tarballUrl}: ${String(response.status)} ${response.statusText}`
  );
}
const archive = new Uint8Array(await response.arrayBuffer());
verifyDigest(archive, integrity);
verifyDigest(archive, `sha1-${Buffer.from(sha1, "hex").toString("base64")}`);

const document = expectRecord(
  JSON.parse(extractTarFile(gunzipSync(archive), "package/css.json")),
  "package/css.json"
);
validateEverySyntax(document);

const catalog = {
  properties: expectArray(document.properties, "properties").map(
    (value, index) => selectProperty(value, `properties[${String(index)}]`)
  ),
  atrules: expectArray(document.atrules, "atrules").map(
    (value, index) => selectAtRule(value, `atrules[${String(index)}]`)
  ),
  functions: expectArray(document.functions, "functions").map(
    (value, index) => selectGrammar(value, `functions[${String(index)}]`)
  ),
  selectors: expectArray(document.selectors, "selectors").map(
    (value, index) => selectGrammar(value, `selectors[${String(index)}]`)
  ),
  types: expectArray(document.types, "types").map(
    (value, index) => selectGrammar(value, `types[${String(index)}]`)
  )
};

const output = `// Generated by scripts/generate/css-data.mjs from ${packageName}.
// Source integrity: ${integrity}
// Do not edit this file directly.

import type { CssWebrefData } from "../grammar/catalog-types.ts";

export const CSS_WEBREF_DATA = ${JSON.stringify(catalog, null, 2)} as const satisfies CssWebrefData;
`;

if (check) {
  const current = await readFile(outputUrl, "utf8");
  if (current !== output) {
    throw new Error(
      "Generated CSS data is stale. Run `npm run generate:css-data` and commit the result."
    );
  }
  process.stdout.write(`verified ${packageName} generated data\n`);
} else {
  await mkdir(new URL("src/internal/generated/", root), { recursive: true });
  await writeFile(outputUrl, output, "utf8");
  process.stdout.write(`generated ${packageName} CSS data\n`);
}

function selectProperty(value, path) {
  const record = expectRecord(value, path);
  return compact({
    name: expectString(record.name, `${path}.name`),
    href: expectString(record.href, `${path}.href`),
    styleDeclaration: expectStringArray(
      record.styleDeclaration,
      `${path}.styleDeclaration`
    ),
    syntax: optionalString(record.syntax, `${path}.syntax`),
    legacyAliasOf: optionalString(record.legacyAliasOf, `${path}.legacyAliasOf`),
    longhands: optionalStringArray(record.longhands, `${path}.longhands`),
    resetLonghands: optionalStringArray(
      record.resetLonghands,
      `${path}.resetLonghands`
    ),
    initial: optionalString(record.initial, `${path}.initial`),
    appliesTo: optionalString(record.appliesTo, `${path}.appliesTo`),
    inherited: optionalString(record.inherited, `${path}.inherited`),
    percentages: optionalString(record.percentages, `${path}.percentages`),
    computedValue: optionalString(record.computedValue, `${path}.computedValue`),
    animationType: optionalString(record.animationType, `${path}.animationType`),
    canonicalOrder: optionalString(record.canonicalOrder, `${path}.canonicalOrder`)
  });
}

function selectAtRule(value, path) {
  const record = expectRecord(value, path);
  return compact({
    name: expectString(record.name, `${path}.name`),
    href: expectString(record.href, `${path}.href`),
    syntax: optionalString(record.syntax, `${path}.syntax`),
    descriptors: expectArray(record.descriptors, `${path}.descriptors`).map(
      (descriptor, index) => {
        const descriptorPath = `${path}.descriptors[${String(index)}]`;
        const item = expectRecord(descriptor, descriptorPath);
        return compact({
          name: expectString(item.name, `${descriptorPath}.name`),
          href: expectString(item.href, `${descriptorPath}.href`),
          syntax: optionalString(item.syntax, `${descriptorPath}.syntax`),
          initial: optionalString(item.initial, `${descriptorPath}.initial`)
        });
      }
    )
  });
}

function selectGrammar(value, path) {
  const record = expectRecord(value, path);
  return compact({
    name: expectString(record.name, `${path}.name`),
    href: expectString(record.href, `${path}.href`),
    syntax: optionalString(record.syntax, `${path}.syntax`),
    for: optionalStringArray(record.for, `${path}.for`)
  });
}

function compact(value) {
  return Object.fromEntries(
    Object.entries(value).filter((entry) => entry[1] !== undefined)
  );
}

function validateEverySyntax(value, path = "css.json") {
  if (Array.isArray(value)) {
    value.forEach((item, index) => validateEverySyntax(item, `${path}[${String(index)}]`));
    return;
  }
  if (!isRecord(value)) return;
  for (const [name, child] of Object.entries(value)) {
    const childPath = `${path}.${name}`;
    if (name === "syntax") {
      const syntax = expectString(child, childPath);
      try {
        parseCssValueDefinition(syntax);
      } catch (error) {
        throw new Error(`Unsupported value definition at ${childPath}: ${syntax}`, {
          cause: error
        });
      }
    }
    validateEverySyntax(child, childPath);
  }
}

function extractTarFile(archive, wantedPath) {
  let offset = 0;
  while (offset + 512 <= archive.byteLength) {
    const header = archive.subarray(offset, offset + 512);
    const name = readTarString(header, 0, 100);
    if (name.length === 0) break;
    const prefix = readTarString(header, 345, 155);
    const path = prefix.length === 0 ? name : `${prefix}/${name}`;
    const sizeText = readTarString(header, 124, 12).trim();
    const size = Number.parseInt(sizeText, 8);
    if (!Number.isSafeInteger(size) || size < 0) {
      throw new Error(`Invalid tar entry size for ${path}.`);
    }
    const contentStart = offset + 512;
    const contentEnd = contentStart + size;
    if (contentEnd > archive.byteLength) {
      throw new Error(`Truncated tar entry ${path}.`);
    }
    if (path === wantedPath) {
      return new TextDecoder("utf-8", { fatal: true }).decode(
        archive.subarray(contentStart, contentEnd)
      );
    }
    offset = contentStart + Math.ceil(size / 512) * 512;
  }
  throw new Error(`The archive does not contain ${wantedPath}.`);
}

function readTarString(header, start, length) {
  const bytes = header.subarray(start, start + length);
  const zero = bytes.indexOf(0);
  return new TextDecoder("utf-8", { fatal: true }).decode(
    zero < 0 ? bytes : bytes.subarray(0, zero)
  );
}

function verifyDigest(bytes, integrity) {
  const separator = integrity.indexOf("-");
  if (separator < 1) {
    throw new Error(`Invalid integrity value ${integrity}.`);
  }
  const algorithm = integrity.slice(0, separator);
  const expected = integrity.slice(separator + 1);
  const actual = createHash(algorithm).update(bytes).digest("base64");
  if (actual !== expected) {
    throw new Error(`${algorithm} digest mismatch for the pinned WebRef archive.`);
  }
}

function expectRecord(value, path) {
  if (!isRecord(value)) throw new TypeError(`${path} must be an object.`);
  return value;
}

function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function expectArray(value, path) {
  if (!Array.isArray(value)) throw new TypeError(`${path} must be an array.`);
  return value;
}

function expectString(value, path) {
  if (typeof value !== "string" || value.length === 0) {
    throw new TypeError(`${path} must be a non-empty string.`);
  }
  return value;
}

function optionalString(value, path) {
  return value === undefined ? undefined : expectString(value, path);
}

function expectStringArray(value, path) {
  return expectArray(value, path).map((item, index) =>
    expectString(item, `${path}[${String(index)}]`)
  );
}

function optionalStringArray(value, path) {
  return value === undefined ? undefined : expectStringArray(value, path);
}
